name: Manual Run Main Script

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run"
        required: true
        default: "production"
        type: choice
        options:
          - production
          - staging
          - development

jobs:
  run-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run main script
        run: npm run start
        env:
          NODE_ENV: ${{ github.event.inputs.environment }}
          RPC_URL_BASE: ${{ secrets.RPC_URL_BASE }}
          RPC_URL_ARBITRUM: ${{ secrets.RPC_URL_ARBITRUM }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
