name: Run Main Script

on:
  workflow_dispatch: # chạy thủ công
  push:
    branches: [main] # chạy khi push lên main
  schedule: # chạy theo lịch
    - cron: "0 */3 * * *" # mỗi 3 tiếng

jobs:
  run-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Create .env file
        run: |
          echo "Creating .env file with required environment variables"
          touch .env
          echo "# Add your environment variables here" >> .env
          echo "# Example:" >> .env
          echo "# RPC_URL_BASE=https://mainnet.base.org" >> .env
          echo "# RPC_URL_ARBITRUM=https://arb1.arbitrum.io/rpc" >> .env
          echo "# SUPABASE_URL=your_supabase_url" >> .env
          echo "# SUPABASE_ANON_KEY=your_supabase_anon_key" >> .env

      - name: Run main script
        run: npm run start
        env:
          # Thêm các environment variables cần thiết ở đây
          # Hoặc sử dụng GitHub Secrets để bảo mật
          BASE_RPC: ${{ secrets.BASE_RPC }}
          ARB1_RPC: ${{ secrets.ARB1_RPC }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

      - name: Upload logs (optional)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-logs
          path: |
            *.log
            logs/
